version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "melody-woods-water"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10y06n40qgez1"
s3_prefix = "melody-woods-water"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

