AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  melody-woods-water

  SAM Template for melody-woods-water

Resources:
  supply:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: supply/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Well #3 Pump - Timer/Parameter Control"
            Name: "well3-timer"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "", "reason": {"type": "well3"}}'
            Schedule: cron(0/15 * * * *)
  tank88k:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: 88k_tank/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role:
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Turn On 88k 5hp Pump - 9PM"
            Name: "88kpump-on-9pm"
            Input: '{"pump": "on", "reason": "9PM"}'
            Schedule: cron(00 04,05 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Description: "88k Tank Hourly (5m past) Check"
            Name: "88kpump-hourly"
            Input: '{"pump": "", "reason": "Hourly"}'
            Schedule: cron(05 * * * ? *)
  email:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: email/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
    PermissionToCallLambdaAbove:
      Type: AWS::Lambda::Permission
      DependsOn: email
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref email
        Principal: !Sub 'workmail.${AWS::Region}.amazonaws.com'

Outputs:
  emailArn:
    Value: !GetAtt email.Arn