AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  melody-woods-water

  SAM Template for melody-woods-water

Resources:
  supply:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: supply/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Turn On Well #3 Pump - 9PM"
            Name: "well3-on-9pm"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "on", "reason": {"type": "24hr", "value": "21"}}'
            Schedule: cron(00 04,05 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Description: "Turn Off Well #3 Pump - 10PM"
            Name: "well3-off-10pm"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "off", "reason": {"type": "24hr", "value": "22"}}'
            Schedule: cron(00 05,06 * * ? *)
        Schedule3:
          Type: Schedule
          Properties:
            Description: "Turn Off Well #3 Pump - 3AM"
            Name: "well3-off-3am"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "off", "reason": {"type": "24hr", "value": "03"}}'
            Schedule: cron(00 10,11 * * ? *)
        Schedule4:
          Type: Schedule
          Properties:
            Description: "Turn Off Well #3 Pump - 9AM"
            Name: "well3-off-9am"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "off", "reason": {"type": "24hr", "value": "09"}}'
            Schedule: cron(00 16,17 * * ? *)
        Schedule5:
          Type: Schedule
          Properties:
            Description: "Turn On Spring Pump - 9PM"
            Name: "spring-on-9pm"
            Input: '{"sentinel_name":"TreatmentPlant","pump_name": "Spring Pump", "pump": "on", "reason": {"type": "24hr", "value": "21"}}'
            Schedule: cron(00 04,05 * * ? *)
        Schedule6:
          Type: Schedule
          Properties:
            Description: "Turn Off Spring Pump - 9AM"
            Name: "spring-off-9am"
            Input: '{"sentinel_name":"TreatmentPlant","pump_name": "Spring Pump", "pump": "off", "reason": {"type": "24hr", "value": "09"}}'
            Schedule: cron(00 16,17 * * ? *)
  tank88k:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: 88k_tank/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role:
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Turn On 88k 5hp Pump - 9PM"
            Name: "88kpump-on-9pm"
            Input: '{"pump": "on", "reason": "9PM"}'
            Schedule: cron(00 04,05 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Description: "88k Tank Hourly (5m past) Check"
            Name: "88kpump-hourly"
            Input: '{"pump": "", "reason": "Hourly"}'
            Schedule: cron(05 * * * ? *)
