AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  melody-woods-water

  SAM Template for melody-woods-water

Resources:
  well3:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: supply/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Turn On Well #3 Pump"
            Name: "well3-on"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "on", "reason": "9PM"}'
            Schedule: cron(00 05 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Description: "Turn Off Well #3 Pump"
            Name: "well3-off"
            Input: '{"sentinel_name":"Well#3","pump_name": "#3 Well Pump", "pump": "off", "reason": "9AM"}'
            Schedule: cron(00 17 * * ? *)
        Schedule3:
          Type: Schedule
          Properties:
            Description: "Turn On Spring Pump"
            Name: "spring-on"
            Input: '{"sentinel_name":"TreatmentPlant","pump_name": "Spring Pump", "pump": "on", "reason": "9PM"}'
            Schedule: cron(00 05 * * ? *)
        Schedule4:
          Type: Schedule
          Properties:
            Description: "Turn Off Spring Pump"
            Name: "spring-off"
            Input: '{"sentinel_name":"TreatmentPlant","pump_name": "Spring Pump", "pump": "off", "reason": "9AM"}'
            Schedule: cron(00 17 * * ? *)
  tank88k:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: 88k_tank/
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role:
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Description: "Turn On 88k 5hp Pump - 9PM"
            Name: "88kpump-on"
            Input: '{"pump": "on", "reason": "9PM"}'
            Schedule: cron(00 05 * * ? *)
        Schedule2:
          Type: Schedule
          Properties:
            Description: "88k Tank Hourly (5m past) Check"
            Name: "88kpump-hourly"
            Input: '{"pump": "", "reason": "Hourly"}'
            Schedule: cron(05 * * * ? *)
